apiVersion: v1
kind: Service
metadata:
  name: {{ include "prefect2-prometheus-exporter.fullname" . }}
  labels:
    {{- include "prefect2-prometheus-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "prefect2-prometheus-exporter.selectorLabels" . | nindent 4 }}
